twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['override/bootstrap_4_layout.html.twig']
    globals:
        centrifugo_url: '%env(CENTRIFUGO_WSS_HOST)%/connection/websocket'
